name: Build

on:
  push:
    branches:
      - '**'

jobs:
  build-dev:
    name: Dev
    if: github.ref != 'refs/heads/master'
    uses: ./.github/workflows/build-flavor.yml
    with:
      flavor: dev
      build-type: debug
      retention-days: '10'

  build-prod:
    name: Prod
    if: github.ref == 'refs/heads/master'
    uses: ./.github/workflows/build-flavor.yml
    with:
      flavor: prod
      build-type: release
